version: "3.8"
services:
  db:
    container_name: investing_db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USR}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - "$PWD/postgres"
