[tool.poetry]
name = "server"
version = "0.1.0"
description = ""
authors = ["Yachim <jachym.kohout@gmail.com>"]
license = "gplv3"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flask = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
